language: node_js
node_js: 4.1
env:
  APP_NAME=sphereplayer
before_script:
  - npm install gulp
before_deploy:
  - ./pack.sh
deploy:
  provider: releases
  api_key:
    secure: VxulKzw6iUkMo0/EoJ/3dOyNvjBFtjkqe3mYZmdIqDMjY3c6ptTi589JX/feCBOlPxWQiaFQG0C5sTQSIDDLTIY/9c1nYygB37nCdtwcBNJjfnXF5998evDco6GQYNxPkisA+7lfi3TrlTd/M9+AKJwjw0sqyRHkaPHofcIq52cbHIHmQp+O6jsvJ4k+MEZb402KNQ17jQWjAzQOwJh5zI78Oy79NYV9GhsrN1KsDI6u7+QLjdi6Iy7Mxi2RgKiwMsjjXmTbwgIaEb6Fg9rUF9yI1jZfMt0utffuIcoJPTfW/Q9T/9cMCOf7cytE3n56Fuyp/lFy/Q3UEZB5beA2xazEXSyTTT+dF1FOcoJwGCCJ5D+55rGTa5kluIXKN20TCTCK6pe537BIXshyPbHm3tL3GNnPFoEGozo/cM933qt+UETe5XbFcAmJyXdNUKh3gytpjuOtquqdManI9YZKeRbZHzXy9haou1jRjfk8rUPdPmIV8TjptE0LkJVMJ8S1CllvLsb0yvBreiubBp1MSW6r7hG8X+ogcMR5frYHwp4XN2oud/s2yf7O/3sDjSLFQhe9Izary82VhPZK5Gjoq+RtmIqAvfStMQhBjTephp8ePqlD08FHaMr+JMpYvQrvVOq8f8WBjD7zYNHV0uQxX+T2fqhpDxwzKPLC6qqz4Eg=
  file:
    - $APP_NAME-win32-ia32.zip
    - $APP_NAME-win32-x64.zip
    - $APP_NAME-darwin-x64.zip
  on:
    tags: true
